# Built with Jekyll 3.2.0

# Setup
title:               J0EL L0VERA
tagline:             'Product manager with background in software engineering. Passionate about problem solving, strategy, building new products, and occasionally helping founders.'
description:         'Product manager with background in software engineering. Passionate about problem solving, strategy, building new products, and occasionally helping founders.'
url:                 'https://loverajoel.com'
baseurl:             ''

# About/contact
author:
  name:              Joel Lovera
  url:               https://twitter.com/loverajoel
  email:             joelalovera@gmail.com

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor